server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'farescode'
    url: jdbc:posgresql://localhost:5432/customer
    password: 'password'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl_auto: update
      show_sql: 'true'